/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author user
 */
import DataBase.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import net.proteanit.sql.DbUtils;

public class Filterr extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    final ObservableList<String> checkBoxList1 = FXCollections.observableArrayList();
    final ObservableList<String> checkBoxList2 = FXCollections.observableArrayList();

    /**
     * Creates new form NewJInternalFrame
     */
    public Filterr() {
        initComponents();
        conn = DBconnect.connect();
    }

    private void check() {
        
        if (ict.isSelected()) {
            checkBoxList1.add(ict.getText());
        }
        if (elec.isSelected()) {
            checkBoxList1.add(elec.getText());
        }
        if (mech.isSelected()) {
            checkBoxList1.add(mech.getText());
        }
        if (acc.isSelected()) {
            checkBoxList1.add(acc.getText());
        }
        if (bsc.isSelected()) {
            checkBoxList2.add(bsc.getText());
        }
        if (ba.isSelected()) {
            checkBoxList2.add(ba.getText());
        }
        if (bacc.isSelected()) {
            checkBoxList2.add(bacc.getText());
        }
        if (bee.isSelected()) {
            checkBoxList2.add(bee.getText());
        }
        
    }
    
//    private void ck2(){
//        if (buttonGroup1.isSelected((ButtonModel) calledc)){
//            filt.equals(calledc.getText());
//        }
//        if (buttonGroup1.isSelected((ButtonModel) notAns)){
//            filt.equals(notAns.getText());
//        }
//        if (buttonGroup1.isSelected((ButtonModel) calledc)){
//            filt.equals(calledc.getText());
//        }
//        if (buttonGroup1.isSelected((ButtonModel) selec)){
//            filt.equals(selec.getText());
//        }
//        if (buttonGroup1.isSelected((ButtonModel) rejec)){
//            filt.equals(rejec.getText());
//        }
//        if (buttonGroup1.isSelected((ButtonModel) poolc)){
//            filt.equals(poolc.getText());
//        }
//    }


//    private void set() throws SQLException {
//        
//        
//        String gende = rs.getString("Name");
//        if (gende.equals("Male")) {
//            female.setSelected(true);
//        } else {
//            male.setSelected(true);
//        }
//        String ALvl = (rs.getString("AL"));
//        switch (ALvl) {
//            case "Stream":
//                ALcomb.setSelectedIndex(4);
//            case "Science":
//                ALcomb.setSelectedIndex(3);
//            case "Art":
//                ALcomb.setSelectedIndex(2);
//            case "Commerce":
//                ALcomb.setSelectedIndex(1);
//            case "Tech":
//                ALcomb.setSelectedIndex(0);
//                break;
//        }
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gend = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        ALcomb = new javax.swing.JComboBox<>();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ict = new javax.swing.JCheckBox();
        elec = new javax.swing.JCheckBox();
        mech = new javax.swing.JCheckBox();
        acc = new javax.swing.JCheckBox();
        bsc = new javax.swing.JCheckBox();
        ba = new javax.swing.JCheckBox();
        bacc = new javax.swing.JCheckBox();
        bee = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calledc = new javax.swing.JCheckBox();
        notAns = new javax.swing.JCheckBox();
        selec = new javax.swing.JCheckBox();
        rejec = new javax.swing.JCheckBox();
        poolc = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(815, 521));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(838, 30));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jLabel1)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(815, 521));

        gend.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gend.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("A/L");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Diploma");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Degree");

        male.setBackground(new java.awt.Color(255, 255, 255));
        male.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setBackground(new java.awt.Color(255, 255, 255));
        female.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        ALcomb.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        ALcomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stream", "Science", "Art", "Commerce", "Tech" }));
        ALcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALcombActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(153, 153, 255));
        add.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        add.setText("Search");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 153, 153));
        clear.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        ict.setBackground(new java.awt.Color(255, 255, 255));
        ict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ict.setText("ICT");

        elec.setBackground(new java.awt.Color(255, 255, 255));
        elec.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        elec.setText("Electrical ");

        mech.setBackground(new java.awt.Color(255, 255, 255));
        mech.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        mech.setText("Mechanical ");

        acc.setBackground(new java.awt.Color(255, 255, 255));
        acc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        acc.setText("Account");

        bsc.setBackground(new java.awt.Color(255, 255, 255));
        bsc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bsc.setText("BSc");

        ba.setBackground(new java.awt.Color(255, 255, 255));
        ba.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ba.setText("BA");

        bacc.setBackground(new java.awt.Color(255, 255, 255));
        bacc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bacc.setText("B.Acc.");

        bee.setBackground(new java.awt.Color(255, 255, 255));
        bee.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bee.setText("B.E.E.");
        bee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Search by NIC");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nic", "Name", "Age", "Address", "Phone", "Email", "Gender", "AL", "Diploma", "Degree", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        calledc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(calledc);
        calledc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calledc.setForeground(new java.awt.Color(0, 255, 0));
        calledc.setText("Called");

        notAns.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(notAns);
        notAns.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notAns.setForeground(new java.awt.Color(255, 153, 0));
        notAns.setText("Not Answered");

        selec.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(selec);
        selec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        selec.setForeground(new java.awt.Color(0, 0, 255));
        selec.setText("Selected");

        rejec.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rejec);
        rejec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rejec.setForeground(new java.awt.Color(255, 0, 0));
        rejec.setText("Rejected");

        poolc.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(poolc);
        poolc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        poolc.setForeground(new java.awt.Color(204, 0, 204));
        poolc.setText("Pool");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(calledc)
                .addGap(18, 18, 18)
                .addComponent(notAns)
                .addGap(18, 18, 18)
                .addComponent(selec)
                .addGap(18, 18, 18)
                .addComponent(rejec)
                .addGap(18, 18, 18)
                .addComponent(poolc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calledc)
                    .addComponent(notAns)
                    .addComponent(selec)
                    .addComponent(rejec)
                    .addComponent(poolc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gend)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bsc)
                                .addGap(18, 18, 18)
                                .addComponent(ba)
                                .addGap(18, 18, 18)
                                .addComponent(bacc)
                                .addGap(18, 18, 18)
                                .addComponent(bee))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ict)
                                .addGap(18, 18, 18)
                                .addComponent(elec)
                                .addGap(18, 18, 18)
                                .addComponent(mech)
                                .addGap(18, 18, 18)
                                .addComponent(acc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(male)
                                .addGap(18, 18, 18)
                                .addComponent(female))
                            .addComponent(ALcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)
                        .addGap(370, 370, 370))))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add)
                        .addGap(18, 18, 18)
                        .addComponent(clear)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gend)
                            .addComponent(male)
                            .addComponent(female))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ALcomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ict)
                            .addComponent(elec)
                            .addComponent(mech)
                            .addComponent(acc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bsc)
                            .addComponent(ba)
                            .addComponent(bacc)
                            .addComponent(bee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(278, 278, 278))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sid = jTextField1.getText();

        String qry = "Select * from data where NIC = '"+sid+"' ";
        try {
            pat = conn.prepareStatement(qry);
            rs = pat.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void beeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        female.setSelected(false);
        male.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        check();
//        ck2();OR Status = '"+filt+"'
        String AL = ALcomb.getSelectedItem().toString();
        String qry = "Select * from data where (AL = '" + AL + "' OR Diploma = '"+checkBoxList1+"' OR Degree = '"+checkBoxList2+"') AND Gender = '"+gender+"'";
        try {
            pat = conn.prepareStatement(qry);
            rs = pat.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            checkBoxList1.clear();
            checkBoxList2.clear();
           
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_addActionPerformed

    private void ALcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALcombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALcombActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        gender = "Fmale";
        if (female.isSelected()) {
            male.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        if (male.isSelected()) {
            female.setSelected(false);
        }
    }//GEN-LAST:event_maleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ALcomb;
    private javax.swing.JCheckBox acc;
    private javax.swing.JButton add;
    private javax.swing.JCheckBox ba;
    private javax.swing.JCheckBox bacc;
    private javax.swing.JCheckBox bee;
    private javax.swing.JCheckBox bsc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox calledc;
    private javax.swing.JButton clear;
    private javax.swing.JCheckBox elec;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gend;
    private javax.swing.JCheckBox ict;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton male;
    private javax.swing.JCheckBox mech;
    private javax.swing.JCheckBox notAns;
    private javax.swing.JCheckBox poolc;
    private javax.swing.JCheckBox rejec;
    private javax.swing.JCheckBox selec;
    // End of variables declaration//GEN-END:variables
    private String gender;
    private String filt;
    private String dip;
    private String deg;
    private int age;
    private int checkList;
}
