/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author user
 */
import DataBase.DBconnect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javax.swing.JOptionPane;

public class Update_data extends javax.swing.JInternalFrame {

    Connection conn = null;
    PreparedStatement pat = null;
    ResultSet rs = null;
    final ObservableList<String> checkBoxList1 = FXCollections.observableArrayList();
    final ObservableList<String> checkBoxList2 = FXCollections.observableArrayList();

    /**
     * Creates new form NewJInternalFrame
     */
    public Update_data() {
        initComponents();
        conn = DBconnect.connect();
    }

    private void check() {
        if (ict.isSelected()) {
            checkBoxList1.add(ict.getText());
        }
        if (elec.isSelected()) {
            checkBoxList1.add(elec.getText());
        }
        if (mech.isSelected()) {
            checkBoxList1.add(mech.getText());
        }
        if (acc.isSelected()) {
            checkBoxList1.add(acc.getText());
        }
        if (bsc.isSelected()) {
            checkBoxList2.add(bsc.getText());
        }
        if (ba.isSelected()) {
            checkBoxList2.add(ba.getText());
        }
        if (bacc.isSelected()) {
            checkBoxList2.add(bacc.getText());
        }
        if (bee.isSelected()) {
            checkBoxList2.add(bee.getText());
        }
    }

    private void calAge() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date d = null;
        try {
            d = sdf.parse(dob.getText());
        } catch (ParseException ex) {

        }
        Calendar c = Calendar.getInstance();
        c.setTime(d);
        int year = c.get(Calendar.YEAR);
        int month = c.get(Calendar.MONTH) + 1;
        int date = c.get(Calendar.DATE);
        LocalDate l1 = LocalDate.of(year, month, date);
        LocalDate now1 = LocalDate.now();
        Period diff1 = Period.between(l1, now1);
        age = diff1.getYears();
    }

    private void set() throws SQLException {
        String nm = rs.getString("Name");
            name.setText(nm);
        String id = rs.getString("NIC");
            nic.setText(id);
        String bir = rs.getString("DOB");
            dob.setText(bir);
        String ad = rs.getString("Address");
            address.setText(ad);
        String em = rs.getString("Email");
            email.setText(em);
        String ph = rs.getString("Phone");
            phone.setText(ph);
        String ot = rs.getString("Other");
            other.setText(ot);
        
        String gende = rs.getString("Name");
        if (gende.equals("Male")) {
            female.setSelected(true);
        } else {
            male.setSelected(true);
        }
        String ALvl = (rs.getString("AL"));
        switch (ALvl) {
            case "Stream":
                ALcomb.setSelectedIndex(4);
            case "Science":
                ALcomb.setSelectedIndex(3);
            case "Art":
                ALcomb.setSelectedIndex(2);
            case "Commerce":
                ALcomb.setSelectedIndex(1);
            case "Tech":
                ALcomb.setSelectedIndex(0);
                break;
        }
//        String dip = (rs.getString("Diploma"));
//        switch(dip){
//            case "[ICT]":
//                ict.setSelected(true);
//            case "[ICT]":
//                ict.setSelected(true);
//            case "[ICT]":
//                ict.setSelected(true);
//            case "[ICT]":
//                ict.setSelected(true);
//        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gend = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        ALcomb = new javax.swing.JComboBox<>();
        other = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        ict = new javax.swing.JCheckBox();
        elec = new javax.swing.JCheckBox();
        mech = new javax.swing.JCheckBox();
        acc = new javax.swing.JCheckBox();
        bsc = new javax.swing.JCheckBox();
        ba = new javax.swing.JCheckBox();
        bacc = new javax.swing.JCheckBox();
        bee = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        dateVAL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nicVAL = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(815, 521));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(838, 30));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update_data");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel1)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(815, 521));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("NIC");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Phone");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Date of Birth");

        gend.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        gend.setText("Gender");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("A/L");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Diploma");

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Degree");

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Other Colifications");

        nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicActionPerformed(evt);
            }
        });
        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });

        dob.setToolTipText("yyyy-mm-dd");
        dob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dobKeyReleased(evt);
            }
        });

        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
        });

        male.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        male.setText("Male");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        ALcomb.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        ALcomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stream", "Science", "Art", "Commerce", "Tech" }));
        ALcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALcombActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(153, 153, 255));
        add.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        add.setText("Update");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 153, 153));
        clear.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        ict.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ict.setText("ICT");

        elec.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        elec.setText("Electrical ");

        mech.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        mech.setText("Mechanical ");

        acc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        acc.setText("Account");

        bsc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bsc.setText("BSc");

        ba.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ba.setText("BA");

        bacc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bacc.setText("B.Acc.");

        bee.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bee.setText("B.E.E.");
        bee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beeActionPerformed(evt);
            }
        });

        jLabel13.setText("yyyy-mm-dd");

        dateVAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateVAL.setForeground(new java.awt.Color(255, 0, 0));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));

        nicVAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nicVAL.setForeground(new java.awt.Color(255, 0, 0));

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("NIC");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(gend)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bsc)
                                .addGap(18, 18, 18)
                                .addComponent(ba)
                                .addGap(18, 18, 18)
                                .addComponent(bacc)
                                .addGap(18, 18, 18)
                                .addComponent(bee))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ict)
                                .addGap(18, 18, 18)
                                .addComponent(elec)
                                .addGap(18, 18, 18)
                                .addComponent(mech)
                                .addGap(18, 18, 18)
                                .addComponent(acc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(male)
                                .addGap(18, 18, 18)
                                .addComponent(female))
                            .addComponent(ALcomb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(other, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nicVAL, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                            .addComponent(dateVAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add)
                        .addGap(18, 18, 18)
                        .addComponent(clear))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nicVAL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3)
                                                .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(dateVAL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(phone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gend)
                            .addComponent(male)
                            .addComponent(female))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ALcomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ict)
                            .addComponent(elec)
                            .addComponent(mech)
                            .addComponent(acc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bsc)
                            .addComponent(ba)
                            .addComponent(bacc)
                            .addComponent(bee))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ALcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALcombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALcombActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
        if (male.isSelected()) {
            female.setSelected(false);
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        gender = "Fmale";
        if (female.isSelected()) {
            male.setSelected(false);
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        nic.setText("");
        dob.setText("");
        address.setText("");
        email.setText("");
        phone.setText("");
        other.setText("");
        female.setSelected(false);
        male.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        calAge();
        check();
        String nm = name.getText();
        String id = jTextField1.getText();
        String birth = dob.getText();
        String adres = address.getText();
        String mail = email.getText();
        String mobile = phone.getText();
        String othe = other.getText();
        String AL = ALcomb.getSelectedItem().toString();
        //String ck = ict.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do You Want to Update This Data");
        
        if(a == 0)
        {
        if ("Invalid".equals(dateVAL.getText()) || "Invalid".equals(jLabel14.getText()) || "Invalid".equals(nicVAL.getText())) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Invalid data had added");
        }
        else if((("".equals(gender)))||("".equals(id))||("".equals(nm))||("".equals(birth))||("".equals(adres))||("".equals(mobile))){
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Some data has missing");
        }
        else {
            String qry = "UPDATE data SET Name='" + nm + "' , Age='" + age + "', Address='" + adres + "', Phone='" + mobile + "', Email='" + mail + "', Gender='" + gender + "', AL='" + AL + "', Diploma='" + checkBoxList1 + "', Degree='" + checkBoxList2 + "', Other='" + othe + "', Status='" + "" + "',DOB='" + birth + "' WHERE NIC='" + id + "'";
            checkBoxList1.clear();
            checkBoxList2.clear();
            try {
                pat = conn.prepareStatement(qry);
                pat.execute();
                JOptionPane.showMessageDialog(null, "Succsessful");
            } catch (SQLException ex) {
                Logger.getLogger(Update_data.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        }}
    }//GEN-LAST:event_addActionPerformed

    private void beeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beeActionPerformed

    private void dobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobKeyReleased
        // TODO add your handling code here:
        Date date = null;
        String inputDate = dob.getText();
        try {
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            formatter.setLenient(false);
            date = formatter.parse(inputDate);
            dateVAL.setText("");
        } catch (ParseException e) {
            e.printStackTrace();
            dateVAL.setText("Invalid");
        }
    }//GEN-LAST:event_dobKeyReleased

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        // TODO add your handling code here:
        String ph = phone.getText();
        if (ph.length() > 10||(!(ph.trim().matches("^[0-9]*")))) {
            getToolkit().beep();
            evt.consume();
            jLabel14.setText("Invalid");
        }
        else if(ph.length() < 10){
            jLabel14.setText("Invalid");
        }
            else {
            jLabel14.setText("");
        }
    }//GEN-LAST:event_phoneKeyReleased

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
        // TODO add your handling code here:
        String nic1 = nic.getText();
        
        if (nic1.length() == 10) {
                if (!(nic1.trim().matches("^[0-9]{9}[vV]$"))) {
                    getToolkit().beep();
                    evt.consume();
                    nicVAL.setText("Invalid");
                }else{
            nicVAL.setText("");}
            }
        else if ((nic1.length() < 10)||(nic1.length()<12 && nic1.length()>10) ) {
            //getToolkit().beep();
            evt.consume();
            nicVAL.setText("Invalid");}
        else if ((nic1.length() > 12)||(!(nic1.trim().matches("^[0-9]{12}")))) {
            getToolkit().beep();
            evt.consume();
            nicVAL.setText("Invalid");
        } else{
            nicVAL.setText("");}
    }//GEN-LAST:event_nicKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sid = jTextField1.getText();

        String qry = "Select * from data where NIC = '" + sid + "' ";
        try {
            pat = conn.prepareStatement(qry);
            rs = pat.executeQuery();
            //set();
            if (rs.next()) {
                set();
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ALcomb;
    private javax.swing.JCheckBox acc;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JCheckBox ba;
    private javax.swing.JCheckBox bacc;
    private javax.swing.JCheckBox bee;
    private javax.swing.JCheckBox bsc;
    private javax.swing.JButton clear;
    private javax.swing.JLabel dateVAL;
    private javax.swing.JTextField dob;
    private javax.swing.JCheckBox elec;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel gend;
    private javax.swing.JCheckBox ict;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton male;
    private javax.swing.JCheckBox mech;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nic;
    private javax.swing.JLabel nicVAL;
    private javax.swing.JTextField other;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
    private String gender;
    private String dip;
    private String deg;
    private int age;
    private int checkList;
}
